# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    name: Build & Unit Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore dotnet/service/service.sln
    - name: Build
      run: dotnet build dotnet/service/service.sln --no-restore
    - name: Test
      run: dotnet test dotnet/tests/unit.tests/unit.tests.csproj --no-build --verbosity normal

  integration_tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: build_and_test  # Ensure integration tests run after build_and_test

    steps:
    - uses: actions/checkout@v4
    - name: Setup Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose
    - name: Build Docker Images and Start Services
      run: |
        cd build
        docker-compose up -d 
    - name: Run Integration Tests
      run: dotnet test dotnet/tests/integration.tests/integration.tests.csproj --no-build --verbosity normal
    - name: Tear Down Docker Containers
      run: |
        docker-compose down  # Tear down the services after tests finish
