# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    name: Build & Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      working-directory: ./go
      run: go build -v ./...

    - name: Test
      working-directory: ./go
      run: go test -v $(go list ./... | grep -v '^./tests')

  integration_tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      working-directory: ./go
      run: go build -v ./...

    - name: Build Docker Images and Start Services
      run: docker compose -f ./build/docker-compose.yaml up -d --build go mongo

    - name: Test
      working-directory: ./go
      run: go test -v ./tests/...
    
    - name: Tear Down Docker Containers
      if: always()  
      run: docker compose -f ./build/docker-compose.yaml down 
